### ISSUE TITLE
Ordering of processes does not work

### ISSUE THREAD

**Issue by mstajdohar** [genialis/resolwe#166]
Tested on the QA server:

https://qa.genialis.com/api/process?slug=alignment-bwa-mem&ordering=-version

For the above query, the `alignment-bwa-mem` processes should be sorted by version, descending. The version 16777232 should be at the top, but comes second.

**Comment by mstajdohar** [comment]
The issue was discovered by @jkokosar. Pease fix ASAP.

**Comment by dblenkus** [comment]
There was no option to order processes by version and API simply ignored it. It is hard to write test for something that was missing, because test would also miss this feature :)

**Comment by mstajdohar** [comment]
But this used to work. Test that you add two processes and the second has a higher version. Sorting by version should return the second process first.

**Comment by dblenkus** [comment]
Yes, it used to work implicitly (ordering was not specified) and there were no tests because it just worked. The problem occurred when we explicitly defined ordering options and forgot to add `version`. I can add a test, but I cannot see where in this process it would help :)

**Comment by mstajdohar** [comment]
Well, if we had the test, when you have specified the ordering explicitly, the test would fail. So you would have known you have forgotten to add the version field.

**Comment by dblenkus** [comment]
At the moment when we just enabled ordering and haven't specified how exactly it should work, we surely wouldn't add tests. And if we would add them when ordering was explicitly defined, it would be too late :).
I will add a test, but just for this use-case.
