### ISSUE TITLE
Process crashes if rendered data name is too long

### ISSUE THREAD

**Issue by dblenkus** [genialis/resolwe#179]
After process is done, names of all child objects are re-rendered. If any of the names is longer than 100 characters (limit specified in name field), process crashes.

Names of data object should probably be trimmed to that limit. Increasing of the limit should also be considered (in combination with trimming).

**Comment by mstajdohar** [comment]
@evasardina, how many characters should we allow for the sample/data object name? The limit is not 100 characters. In my opinion, names should be short so they fit in a table cell.

I would not increase the length. What is a good solution then? Automatic trimming? Error or warning on the data object? Automatic trimming + warning? No trimming + error?

@jkokosar, @kostko, @tjanez, please share your opinion.

**Comment by kostko** [comment]
I would go for automatic trimming.
