### ISSUE TITLE
A recent change in resolwe.test.TransactionTestCase broke Resolwe Bioinformatics tests

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe#250]
Currently, [Resolwe Bioinformatics](https://github.com/genialis/resolwe-bio/)' tests are failing with the following pattern:

```
mv /home/biolinux/upload/variant_calling_filtering.vcf.gz_c54c89b0-4005-4fa7-b74f-137cc7062e0f variant_calling_filtering.vcf.gz
mv: cannot create regular file 'variant_calling_filtering.vcf.gz': Permission denied
```
For an example, see [master build #21](https://ci.genialis.com/job/genialis-github/job/resolwe-bio/job/master/21/console).

The underlying problem is that [this code change](https://github.com/genialis/resolwe/commit/67a3b6901c4a16f043a3465e227462cc4730802c#diff-751e768e9b3f5f3a8d516ea9fb242a98R100) broke the Docker volume mapping for Resolwe Bioinformatics tests since [they use `/home/biolinux/data` as the mapping's `dest` directory](https://github.com/genialis/resolwe-bio/blob/c83470588679ea8e677c3d0a02b7e65aa23d1578/tests/settings.py#L119).

**Comment by mstajdohar** [comment]
@tjanez Was this fixed?

**Comment by mstajdohar** [comment]
@tjanez Ping

**Comment by tjanez** [comment]
Yes, this was fixed and [Resolwe Bioinformatics' test project's settings now use `/data` as data object's `dest` directory](https://github.com/genialis/resolwe-bio/blob/729ec00a5c61023b3afb7af531a3cccd9b2f9b3c/tests/settings.py#L121).
