### ISSUE TITLE
Basket for sample comparison not working in Firefox

### ISSUE THREAD

**Issue by JenkoB** [genialis/resolwe#257]
It happens that I have tested visualizations for lexogen in Firefox and noticed it is not working, while in Chrome it is working perfectly.

Link to page
https://qa.genialis.com/lexogen/visual_analysis?_b=38801ffd-29c5-4acd-8457-1012b7688197&_s=03859e26-9568-45c6-a9a3-eced70d304c7
![screenshot from 2017-03-30 13-51-56](https://cloud.githubusercontent.com/assets/9283107/24502957/554114e8-1550-11e7-92e0-f309301b4f4f.png)

**Comment by lukaw3d** [comment]
Try to clear cache?

**Comment by mstajdohar** [comment]
This could be permissions issue. You are logged in as Barbara Jenko on Chrome, but as Demo Lexogen on Firefox. Work OK in my Firefox and logged-in as me (a superuser).
