### ISSUE TITLE
Pin Pylint version

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe#269]
The upstream release of [Pylint 1.7.0](https://pylint.readthedocs.io/en/latest/whatsnew/1.7.html) broke our [Resolwe `master` tests](https://travis-ci.org/genialis/resolwe/jobs/221783823).

To avoid this in the future,  we should pin the Pylint requirement (to `~=1.7.0` or `~=1.6.4` if we decide to postpone fixing Pylint 1.7.0 warning/errors) in `setup.py` to avoid this and similar fallouts in the future.

**Comment by mstajdohar** [comment]
The Pylint requirement was pinned.
