### ISSUE TITLE
Don't use stdout for communication between executor and its subprocess

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe#289]
Currently, [executor communicates with its subprocess via reading subprocess' stdout and parsing JSON (and other specially formatted) lines from it](https://github.com/genialis/resolwe/blob/master/resolwe/flow/executors/__init__.py#L178-L253).

This can cause many subtle problems, like the out encountered in [#220](https://github.com/genialis/resolwe/pull/220#issuecomment-302466959), where the progress of the `curl` command written to the standard output interleaved with the JSON outputted by the subsequent `echo` command. The executor failed to parse JSON from a standard output line like:
```
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"collection-list": [{"slug":"collection-foo","name":"collection-foo","description":"","settings":{},"descriptor_schema":null,"descriptor":{},"data":[50],"contributor":{"id":117,"username":"contributor","first_name":"","last_name":""},"id":31,"created":"2017-03-24T03:37:17.417596","modified":"2017-03-24T03:37:17.417634","descriptor_dirty":false,"permissions":[{"permissions":["view"],"type":"public"}]}]}
```
which caused the process to not work as expected.

We should implement a more robust solution for communication between executor and its subprocess.

**Comment by mstajdohar** [comment]
This was planned in [epic](https://trello.com/c/45N0QUjA).
