### ISSUE TITLE
Debug why test_memory_resource executor test fails on Travis CI and fix it

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe#324]
Since commit eb65922 which updated the toolkit's base Docker image to Fedora 26, the [`test_memory_resource` executor test](https://github.com/genialis/resolwe/blob/b42cfe2c67440f710d046b28efb2a7105c04e76d/resolwe/flow/tests/test_executors.py#L168-L172) has been [consistently](https://travis-ci.org/genialis/resolwe/builds/254789560) [failing](https://travis-ci.org/genialis/resolwe/builds/254843094) on [Travis CI](https://travis-ci.org/genialis/resolwe/builds/255247548). Find out what is going on and fix it.

After this is done, we can revert commit d169695.

**Comment by mstajdohar** [comment]
Is this still an issue?

**Comment by mstajdohar** [comment]
@tjanez Is this still relevant?
