### ISSUE TITLE
Restrict field names to /^[a-zA-Z][a-zA-Z0-9_]*$/ 

### ISSUE THREAD

**Issue by mstajdohar** [genialis/resolwe#339]
Write tests. Identify existing fields with invalid name. Discuss data migration.

**Comment by mstajdohar** [comment]
@kostko Do you have the bandwidth to tackle this?

**Comment by kostko** [comment]
Yes, I can look into this.

**Comment by mstajdohar** [comment]
Maybe tackle this first https://github.com/genialis/genialis-apps/issues/742 as it affects the user experience.
