### ISSUE TITLE
Filename collision in multiple re-import calls

### ISSUE THREAD

**Issue by mzganec** [genialis/resolwe#371]
In processes which have multiple `basic:file` input fields and use `re-import` function, the following scenario can occur. Suppose that a user has two different files with the same file name stored in different directories. The user then calls a process with two input `basic:file` fields, providing the two aforementioned files. If the first uploaded file is not manually renamed in the process before the second `re-import` call, the first file is overwritten by the second file during the second `re-import` call. Although the process operates with two different `basic:file` input fields, they both point to the same file in the `data` directory.

Two examples of affected processes are `upload-expression` and `upload-fastq-paired`. 

It is unwise to expect that issue will be taken care of manually in each process. A general solution is needed.

**Comment by mstajdohar** [comment]
@dblenkus Please suggest solution ideas. Maybe we should not allow two data objects with the same file_temp.

**Comment by mstajdohar** [comment]
@dblenkus Is this still relevant?
