### ISSUE TITLE
Harden the manager to properly handle broken Data objects

### ISSUE THREAD

**Issue by dblenkus** [genialis/resolwe#379]
One broken Data object in `RESOLVING` state can break the manager and prevent any new Data object from being created.

There are two things that should be implemented:

- manager should continue processing Data objects, even after encountering a broken object
- Data objects that cannot be processed by the manager should be set to the `ERROR` status to prevent filling up the queue

**Comment by mstajdohar** [comment]
Is this still relevant?

**Comment by mstajdohar** [comment]
@dblenkus ping
