### ISSUE TITLE
Should get_or_create only work with Data objects which status is Data.STATUS_DONE?

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe#383]
Currently, if processing of a `Data` object fails and the `Data` object has status  `Data.STATUS_ERROR`, it is perfectly valid when a [new `Data` object is created with the `get_or_create` keyword argument](https://github.com/genialis/resolwe/blob/edb2dfec900b6eee42bc11b238201b0cb41b979c/resolwe/flow/views/data.py#L75-L94).

In practice, this means if a `Data` object's processing failed due to an external resource issue, users will constantly receive the same *broken* `Data` object when they use `get_or_create`.

**Comment by mstajdohar** [comment]
But what's the point of computing the object again in the same environment? Just burning more resources with the same end result. Two things make the analysis successful, relaxing the resources or refactoring the process. The latter is already accounted for in the data object's checksum. Changing the process invalidates the checksum test. I suggest we add resource constraints to the checksum too.

**Comment by mstajdohar** [comment]
@dblenkus What is your opinion on this?
