### ISSUE TITLE
Random failure with resolwe.permissions.tests.test_data.DataTestCase.test_post

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe#53]
@dblenkus, @mstajdohar: The first build of PR #52  [failed with an unrelated error for `resolwe.permissions.tests.test_data.DataTestCase.test_post`](https://ci.genialis.com/job/resolwe-pull_requests/269/TOXENV=py34,label=master/testReport/junit/resolwe.permissions.tests.test_data/DataTestCase/test_post/):

```
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/resolwe-pull_requests/workspace/TOXENV/py34/label/master/resolwe/permissions/tests/test_data.py", line 63, in test_post
    self.assertTrue(datetime.now() - d.modified < timedelta(seconds=1))
AssertionError: False is not true
```

Is 1 s always enough? At first sight, it seems using an arbitrary number like this is prone to an error.

**Comment by mstajdohar** [comment]
Is this still a problem. Is this reproducible?

**Comment by mstajdohar** [comment]
@tjanez Ping

**Comment by tjanez** [comment]
I haven't noticed this problem in a long time, so I think we can close this for now.
